version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10

- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
  open-pull-requests-limit: 10

- package-ecosystem: cargo
  directory: "/statime-stm32/"
  schedule:
    interval: "monthly"
  groups:
    stm32-example:
      patterns:
        - "*"