[package]
name = "ptp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = { version = "0.5.1", default-features = false }
fixed = "1.11.0"
arrayvec = { version = "0.7.2", default-features = false }
nix = { git = "https://github.com/nix-rust/nix.git", branch = "master" }
time = "0.3.5"
getset = "0.1.2"
libc = { version = "0.2.112", features = ["extra_traits"] }
bitflags = "1.3.2"
