loglevel = "info" # Other values include trace, debug, warn and error

#mode = "Transparant" # Ordinary, Boundary, Transparent (not currently supported)

sdo-id = "0"
domain = 0
priority1 = 255
priority2 = 255
#hardware_clock =

[[port]]
interface = "enp0s31f6"
announce_interval = 1
sync_interval = 0
announce_receipt_timeout = 3
delay_asymetry = 0
delay_mechanism = 0

[[port]]
interface = "enp0s31f6"
announce_interval = 1
sync_interval = 0
announce_receipt_timeout = 3
delay_asymetry = 0
delay_mechanism = 0
