loglevel = "info" # Other values include trace, debug, warn and error

[observability]
loglevel = "info" # Other values include trace, debug, warn and error
observation-path = "/var/run/statime/observe"

# Add one of these per network interface in your system
[[port]]
interface = "<interfacename>"
#network-mode = "ipv4" #can also be ipv6 or ethernet
# If the network interface has hardware clock support, you can enable it with
#hardware-clock = "/dev/ptp<hardware clock number>"
