[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32F767ZITx"
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
  # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
  "-C", "link-arg=--nmagic",
]


[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info,stm32_ptp=trace"
