[package]
name = "statime-linux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.8", features = ["derive"] }
fern = { version = "0.6.2", features = ["colored"] }
libc = { version = "0.2.147", features = ["extra_traits"] }
log = "0.4.19"
statime = { path = "../statime" }
thiserror = "1.0.43"
tokio = { version = "1.29", features = ["full"] }
