[package]
name = "statime-linux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
fixed = "1.11.0"
libc = { version = "0.2.112", features = ["extra_traits"] }
log = "0.4.14"
nix = { git = "https://github.com/nix-rust/nix.git", branch = "master" }
statime = { path = "../statime" }
thiserror = "1.0.30"
