[package]
name = "statime-linux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = { version = "0.7.2", default-features = false }
bitflags = "2.2.1"
fixed = "1.23.1"
libc = { version = "0.2.141", features = ["extra_traits"] }
log = "0.4.14"
nix = "0.26.1"
statime = { path = "../statime" }
thiserror = "1.0.40"
tokio = { version = "1.27", features = ["time", "net", "macros"] }
