[package]
name = "statime-linux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = { version = "0.7.4", default-features = false }
clap = { version = "4.3.8", features = ["derive"] }
fern = { version = "0.6.2", features = ["colored"] }
libc = { version = "0.2.147", features = ["extra_traits"] }
log = "0.4.19"
statime = { path = "../statime" }
thiserror = "1.0.43"
pin-project-lite = "0.2.11"
tokio = { version = "1.29", features = ["net", "rt-multi-thread", "time", "macros"] }
rand = { version = "0.8.5", default-features = false, features = ["std", "std_rng"] }
clock-steering = { git = "https://github.com/pendulum-project/clock-steering.git", rev = "4628f18" }
