#!/bin/sh

set -e

STATIME_HOME="/var/lib/statime/"
STATIME_USER="statime"

create_user() {
    if ! id ${STATIME_USER} > /dev/null 2>&1; then
        adduser --system --home "${STATIME_HOME}" --group ${STATIME_USER}
    fi
}

case "$1" in
configure)
    create_user
    ;;
esac

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
    if deb-systemd-helper debian-installed statime.service; then
        # This will only remove masks created by d-s-h on package removal.
        deb-systemd-helper unmask statime.service >/dev/null || true

        if deb-systemd-helper --quiet was-enabled statime.service; then
            # Create new symlinks, if any.
            deb-systemd-helper enable statime.service >/dev/null || true
        fi
    fi

    # Update the statefile to add new symlinks (if any), which need to be cleaned
    # up on purge. Also remove old symlinks.
    deb-systemd-helper update-state statime.service >/dev/null || true
fi

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action statime.service >/dev/null || true
	fi

    if [ -d /run/udev ]; then
        udevadm control -R
        udevadm trigger
    fi
fi

#DEBHELPER#
