#!/bin/sh
set -e

if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
    deb-systemd-invoke stop statime.service >/dev/null || true
    deb-systemd-invoke stop statime-metrics-exporter.service >/dev/null || true
fi
